/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:04b76e69-b3ca-45e1-9c65-d7fe44b9b5b8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_avVL7lId6",
    "aws_user_pools_web_client_id": "3o3l2ghf15j30ddcu5ckjmupia",
    "oauth": {}
};


export default awsmobile;
